package main

import (
	"strings"
	"bufio"
	"os"
	"path/filepath"
)

const files string = `/XXXXX
/usr/bin/dpkg
/usr/bin/dpkg-deb
/usr/bin/dpkg-divert
/usr/bin/dpkg-maintscript-helper
/usr/bin/dpkg-query
/usr/bin/dpkg-split
/usr/bin/dpkg-statoverride
/usr/bin/dpkg-trigger
/usr/bin/update-alternatives
/usr/share/dpkg
/etc/dpkg
/usr/lib/dpkg
/XXXXX
/usr/bin/apt
/usr/bin/apt-cache
/usr/bin/apt-cdrom
/usr/bin/apt-config
/usr/bin/apt-get
/usr/bin/apt-key
/usr/bin/apt-mark
/usr/lib/apt
/usr/bin/debsig-verify
/sbin/start-stop-daemon
/etc/apt
/XXXXX
/usr/bin/perl
/usr/bin/perl5.30.0
/usr/lib/x86_64-linux-gnu/perl-base/AutoLoader.pm
/usr/lib/x86_64-linux-gnu/perl-base/Carp.pm
/usr/lib/x86_64-linux-gnu/perl-base/Carp/Heavy.pm
/usr/lib/x86_64-linux-gnu/perl-base/Config.pm
/usr/lib/x86_64-linux-gnu/perl-base/Config_git.pl
/usr/lib/x86_64-linux-gnu/perl-base/Config_heavy.pl
/usr/lib/x86_64-linux-gnu/perl-base/Cwd.pm
/usr/lib/x86_64-linux-gnu/perl-base/DynaLoader.pm
/usr/lib/x86_64-linux-gnu/perl-base/Errno.pm
/usr/lib/x86_64-linux-gnu/perl-base/Exporter.pm
/usr/lib/x86_64-linux-gnu/perl-base/Exporter/Heavy.pm
/usr/lib/x86_64-linux-gnu/perl-base/Fcntl.pm
/usr/lib/x86_64-linux-gnu/perl-base/File/Basename.pm
/usr/lib/x86_64-linux-gnu/perl-base/File/Glob.pm
/usr/lib/x86_64-linux-gnu/perl-base/File/Path.pm
/usr/lib/x86_64-linux-gnu/perl-base/File/Spec.pm
/usr/lib/x86_64-linux-gnu/perl-base/File/Spec/Unix.pm
/usr/lib/x86_64-linux-gnu/perl-base/File/Temp.pm
/usr/lib/x86_64-linux-gnu/perl-base/FileHandle.pm
/usr/lib/x86_64-linux-gnu/perl-base/Getopt/Long.pm
/usr/lib/x86_64-linux-gnu/perl-base/Hash/Util.pm
/usr/lib/x86_64-linux-gnu/perl-base/IO.pm
/usr/lib/x86_64-linux-gnu/perl-base/IO/File.pm
/usr/lib/x86_64-linux-gnu/perl-base/IO/Handle.pm
/usr/lib/x86_64-linux-gnu/perl-base/IO/Pipe.pm
/usr/lib/x86_64-linux-gnu/perl-base/IO/Seekable.pm
/usr/lib/x86_64-linux-gnu/perl-base/IO/Select.pm
/usr/lib/x86_64-linux-gnu/perl-base/IO/Socket.pm
/usr/lib/x86_64-linux-gnu/perl-base/IO/Socket/INET.pm
/usr/lib/x86_64-linux-gnu/perl-base/IO/Socket/IP.pm
/usr/lib/x86_64-linux-gnu/perl-base/IO/Socket/UNIX.pm
/usr/lib/x86_64-linux-gnu/perl-base/IPC/Open2.pm
/usr/lib/x86_64-linux-gnu/perl-base/IPC/Open3.pm
/usr/lib/x86_64-linux-gnu/perl-base/List/Util.pm
/usr/lib/x86_64-linux-gnu/perl-base/POSIX.pm
/usr/lib/x86_64-linux-gnu/perl-base/Scalar/Util.pm
/usr/lib/x86_64-linux-gnu/perl-base/SelectSaver.pm
/usr/lib/x86_64-linux-gnu/perl-base/Socket.pm
/usr/lib/x86_64-linux-gnu/perl-base/Symbol.pm
/usr/lib/x86_64-linux-gnu/perl-base/Text/ParseWords.pm
/usr/lib/x86_64-linux-gnu/perl-base/Text/Tabs.pm
/usr/lib/x86_64-linux-gnu/perl-base/Text/Wrap.pm
/usr/lib/x86_64-linux-gnu/perl-base/Tie/Hash.pm
/usr/lib/x86_64-linux-gnu/perl-base/XSLoader.pm
/usr/lib/x86_64-linux-gnu/perl-base/attributes.pm
/usr/lib/x86_64-linux-gnu/perl-base/auto/Cwd/Cwd.so
/usr/lib/x86_64-linux-gnu/perl-base/auto/Fcntl/Fcntl.so
/usr/lib/x86_64-linux-gnu/perl-base/auto/File/Glob/Glob.so
/usr/lib/x86_64-linux-gnu/perl-base/auto/Hash/Util/Util.so
/usr/lib/x86_64-linux-gnu/perl-base/auto/IO/IO.so
/usr/lib/x86_64-linux-gnu/perl-base/auto/List/Util/Util.so
/usr/lib/x86_64-linux-gnu/perl-base/auto/POSIX/POSIX.so
/usr/lib/x86_64-linux-gnu/perl-base/auto/Socket/Socket.so
/usr/lib/x86_64-linux-gnu/perl-base/auto/attributes/attributes.so
/usr/lib/x86_64-linux-gnu/perl-base/auto/re/re.so
/usr/lib/x86_64-linux-gnu/perl-base/base.pm
/usr/lib/x86_64-linux-gnu/perl-base/bytes.pm
/usr/lib/x86_64-linux-gnu/perl-base/bytes_heavy.pl
/usr/lib/x86_64-linux-gnu/perl-base/constant.pm
/usr/lib/x86_64-linux-gnu/perl-base/feature.pm
/usr/lib/x86_64-linux-gnu/perl-base/fields.pm
/usr/lib/x86_64-linux-gnu/perl-base/integer.pm
/usr/lib/x86_64-linux-gnu/perl-base/lib.pm
/usr/lib/x86_64-linux-gnu/perl-base/locale.pm
/usr/lib/x86_64-linux-gnu/perl-base/overload.pm
/usr/lib/x86_64-linux-gnu/perl-base/overloading.pm
/usr/lib/x86_64-linux-gnu/perl-base/parent.pm
/usr/lib/x86_64-linux-gnu/perl-base/re.pm
/usr/lib/x86_64-linux-gnu/perl-base/strict.pm
/usr/lib/x86_64-linux-gnu/perl-base/unicore/Heavy.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/Age.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/Bc.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/Bmg.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/Bpb.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/Bpt.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/Cf.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/Digit.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/Ea.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/EqUIdeo.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/Fold.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/GCB.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/Gc.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/Hst.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/InPC.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/InSC.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/Isc.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/Jg.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/Jt.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/Lb.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/Lc.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/Lower.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/NFCQC.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/NFDQC.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/NFKCCF.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/NFKCQC.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/NFKDQC.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/Na1.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/NameAlia.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/Nt.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/Nv.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/PerlDeci.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/SB.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/Sc.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/Scx.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/Tc.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/Title.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/Uc.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/Upper.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/Vo.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/WB.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/_PerlLB.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/To/_PerlSCX.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Age/NA.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Age/V100.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Age/V11.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Age/V110.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Age/V120.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Age/V20.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Age/V30.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Age/V31.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Age/V32.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Age/V40.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Age/V41.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Age/V50.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Age/V51.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Age/V52.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Age/V60.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Age/V61.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Age/V70.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Age/V80.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Age/V90.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Alpha/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Bc/AL.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Bc/AN.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Bc/B.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Bc/BN.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Bc/CS.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Bc/EN.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Bc/ES.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Bc/ET.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Bc/L.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Bc/NSM.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Bc/ON.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Bc/R.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Bc/WS.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/BidiC/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/BidiM/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Blk/NB.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Bpt/C.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Bpt/N.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Bpt/O.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/CE/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/CI/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/CWCF/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/CWCM/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/CWKCF/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/CWL/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/CWT/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/CWU/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Cased/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Ccc/A.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Ccc/AL.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Ccc/AR.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Ccc/ATAR.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Ccc/B.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Ccc/BR.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Ccc/DB.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Ccc/NK.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Ccc/NR.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Ccc/OV.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Ccc/VR.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/CompEx/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/DI/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Dash/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Dep/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Dia/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Dt/Com.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Dt/Enc.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Dt/Fin.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Dt/Font.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Dt/Init.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Dt/Iso.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Dt/Med.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Dt/Nar.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Dt/Nb.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Dt/NonCanon.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Dt/Sqr.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Dt/Sub.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Dt/Sup.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Dt/Vert.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Ea/A.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Ea/H.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Ea/N.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Ea/Na.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Ea/W.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Ext/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/GCB/CN.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/GCB/EX.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/GCB/LV.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/GCB/LVT.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/GCB/PP.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/GCB/SM.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/GCB/XX.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/C.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/Cf.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/Cn.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/L.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/LC.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/Ll.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/Lm.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/Lo.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/Lu.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/M.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/Mc.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/Me.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/Mn.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/N.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/Nd.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/Nl.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/No.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/P.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/Pc.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/Pd.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/Pe.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/Pf.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/Pi.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/Po.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/Ps.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/S.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/Sc.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/Sk.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/Sm.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/So.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/Z.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Gc/Zs.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/GrBase/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/GrExt/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Hex/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Hst/NA.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Hyphen/T.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/IDC/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/IDS/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Ideo/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/In/10_0.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/In/11_0.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/In/12_0.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/In/12_1.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/In/2_0.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/In/2_1.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/In/3_0.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/In/3_1.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/In/3_2.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/In/4_0.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/In/4_1.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/In/5_0.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/In/5_1.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/In/5_2.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/In/6_0.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/In/6_1.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/In/6_2.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/In/6_3.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/In/7_0.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/In/8_0.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/In/9_0.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InPC/Bottom.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InPC/Left.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InPC/LeftAndR.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InPC/NA.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InPC/Overstru.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InPC/Right.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InPC/Top.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InPC/TopAndBo.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InPC/TopAndL2.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InPC/TopAndLe.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InPC/TopAndRi.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InPC/VisualOr.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InSC/Avagraha.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InSC/Bindu.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InSC/Cantilla.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InSC/Consona2.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InSC/Consona3.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InSC/Consona4.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InSC/Consona5.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InSC/Consona6.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InSC/Consona7.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InSC/Consonan.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InSC/Invisibl.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InSC/Nukta.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InSC/Number.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InSC/Other.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InSC/PureKill.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InSC/Syllable.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InSC/ToneMark.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InSC/Virama.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InSC/Visarga.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InSC/Vowel.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InSC/VowelDep.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/InSC/VowelInd.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Jg/Ain.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Jg/Alef.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Jg/Beh.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Jg/Dal.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Jg/FarsiYeh.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Jg/Feh.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Jg/Gaf.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Jg/Hah.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Jg/HanifiRo.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Jg/Kaf.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Jg/Lam.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Jg/NoJoinin.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Jg/Qaf.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Jg/Reh.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Jg/Sad.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Jg/Seen.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Jg/Waw.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Jg/Yeh.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Jt/C.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Jt/D.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Jt/L.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Jt/R.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Jt/T.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Jt/U.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Lb/AI.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Lb/AL.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Lb/BA.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Lb/BB.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Lb/CJ.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Lb/CL.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Lb/CM.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Lb/EB.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Lb/EX.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Lb/GL.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Lb/ID.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Lb/IN.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Lb/IS.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Lb/NS.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Lb/NU.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Lb/OP.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Lb/PO.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Lb/PR.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Lb/QU.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Lb/SA.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Lb/XX.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Lower/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Math/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/NFCQC/M.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/NFCQC/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/NFDQC/N.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/NFDQC/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/NFKCQC/N.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/NFKCQC/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/NFKDQC/N.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/NFKDQC/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nt/Di.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nt/None.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nt/Nu.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/0.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/1.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/10.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/100.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/1000.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/10000.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/100000.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/11.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/12.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/13.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/14.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/15.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/16.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/17.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/18.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/19.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/1_16.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/1_2.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/1_3.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/1_4.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/1_6.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/1_8.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/2.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/20.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/200.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/2000.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/20000.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/2_3.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/3.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/30.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/300.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/3000.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/30000.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/3_16.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/3_4.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/4.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/40.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/400.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/4000.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/40000.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/5.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/50.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/500.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/5000.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/50000.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/6.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/60.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/600.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/6000.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/60000.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/7.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/70.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/700.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/7000.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/70000.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/8.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/80.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/800.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/8000.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/80000.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/9.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/90.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/900.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/9000.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Nv/90000.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/PCM/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/PatSyn/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Perl/Alnum.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Perl/Assigned.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Perl/Blank.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Perl/Graph.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Perl/PerlWord.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Perl/PosixPun.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Perl/Print.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Perl/SpacePer.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Perl/Title.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Perl/Word.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Perl/XPosixPu.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Perl/_PerlAny.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Perl/_PerlCh2.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Perl/_PerlCha.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Perl/_PerlFol.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Perl/_PerlIDC.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Perl/_PerlIDS.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Perl/_PerlIsI.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Perl/_PerlNch.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Perl/_PerlNon.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Perl/_PerlPat.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Perl/_PerlPr2.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Perl/_PerlPro.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Perl/_PerlQuo.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/QMark/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/SB/AT.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/SB/CL.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/SB/EX.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/SB/FO.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/SB/LE.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/SB/LO.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/SB/NU.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/SB/SC.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/SB/ST.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/SB/Sp.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/SB/UP.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/SB/XX.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/SD/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/STerm/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Arab.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Armn.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Beng.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Cprt.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Cyrl.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Deva.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Dupl.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Geor.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Glag.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Gong.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Gonm.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Gran.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Grek.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Gujr.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Guru.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Han.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Hang.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Hira.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Kana.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Knda.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Latn.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Limb.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Linb.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Mlym.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Mong.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Mult.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Orya.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Sinh.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Syrc.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Taml.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Telu.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Zinh.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Sc/Zyyy.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Adlm.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Arab.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Armn.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Beng.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Bhks.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Bopo.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Cakm.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Cham.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Copt.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Cprt.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Cyrl.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Deva.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Dupl.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Ethi.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Geor.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Glag.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Gong.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Gonm.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Gran.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Grek.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Gujr.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Guru.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Han.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Hang.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Hebr.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Hira.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Hmng.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Hmnp.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Kana.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Khar.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Khmr.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Khoj.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Knda.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Kthi.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Lana.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Lao.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Latn.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Limb.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Lina.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Linb.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Mlym.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Mong.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Mult.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Mymr.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Nand.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Orya.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Phlp.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Rohg.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Shrd.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Sind.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Sinh.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Syrc.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Tagb.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Takr.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Talu.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Taml.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Telu.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Thaa.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Tibt.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Tirh.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Xsux.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Yi.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Zinh.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Zyyy.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Scx/Zzzz.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Term/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/UIdeo/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Upper/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Vo/R.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Vo/Tr.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Vo/Tu.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/Vo/U.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/WB/EX.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/WB/Extend.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/WB/FO.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/WB/HL.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/WB/KA.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/WB/LE.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/WB/MB.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/WB/ML.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/WB/MN.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/WB/NU.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/WB/WSegSpac.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/WB/XX.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/XIDC/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/unicore/lib/XIDS/Y.pl
/usr/lib/x86_64-linux-gnu/perl-base/utf8.pm
/usr/lib/x86_64-linux-gnu/perl-base/utf8_heavy.pl
/usr/lib/x86_64-linux-gnu/perl-base/vars.pm
/usr/lib/x86_64-linux-gnu/perl-base/warnings.pm
/usr/lib/x86_64-linux-gnu/perl-base/warnings/register.pm
/XXXXX
/usr/bin/deb-systemd-helper
/usr/bin/deb-systemd-invoke
/usr/sbin/invoke-rc.d
/usr/sbin/service
/usr/sbin/update-rc.d
/XXXXX
/usr/bin/gpgv
/XXXXX
/bin/run-parts
/bin/tempfile
/bin/which
/sbin/installkernel
/usr/bin/ischroot
/usr/bin/savelog
/usr/sbin/add-shell
/usr/sbin/remove-shell
/usr/share/debianutils/shells
/XXXXX
/bin/tar
/etc/rmt
/usr/lib/mime/packages/tar
/usr/sbin/rmt-tar
/usr/sbin/tarcat
/XXXXX
/usr/bin/cmp
/usr/bin/diff
/usr/bin/diff3
/usr/bin/sdiff
/XXXXX
/etc/apt/apt.conf.d/01autoremove
/etc/cron.daily/apt-compat
/etc/kernel/postinst.d/apt-auto-removal
/etc/logrotate.d/apt
/lib/systemd/system/apt-daily-upgrade.service
/lib/systemd/system/apt-daily-upgrade.timer
/lib/systemd/system/apt-daily.service
/lib/systemd/system/apt-daily.timer
/usr/bin/apt
/usr/bin/apt-cache
/usr/bin/apt-cdrom
/usr/bin/apt-config
/usr/bin/apt-get
/usr/bin/apt-key
/usr/bin/apt-mark
/usr/lib/apt/apt-helper
/usr/lib/apt/apt.systemd.daily
/usr/lib/apt/methods/cdrom
/usr/lib/apt/methods/copy
/usr/lib/apt/methods/file
/usr/lib/apt/methods/ftp
/usr/lib/apt/methods/gpgv
/usr/lib/apt/methods/http
/usr/lib/apt/methods/https
/usr/lib/apt/methods/mirror
/usr/lib/apt/methods/mirror+copy
/usr/lib/apt/methods/mirror+file
/usr/lib/apt/methods/mirror+ftp
/usr/lib/apt/methods/mirror+http
/usr/lib/apt/methods/mirror+https
/usr/lib/apt/methods/rred
/usr/lib/apt/methods/rsh
/usr/lib/apt/methods/ssh
/usr/lib/apt/methods/store
/usr/lib/apt/planners/dump
/usr/lib/apt/solvers/dump
/usr/lib/dpkg/methods/apt/desc.apt
/usr/lib/dpkg/methods/apt/install
/usr/lib/dpkg/methods/apt/names
/usr/lib/dpkg/methods/apt/setup
/usr/lib/dpkg/methods/apt/update
/usr/lib/s390x-linux-gnu/libapt-private.so.0.0
/usr/lib/s390x-linux-gnu/libapt-private.so.0.0.0
/usr/share/bash-completion/completions/apt
/XXXXX
/etc/bindresvport.blacklist
/etc/default/nss
/etc/gai.conf
/etc/ld.so.conf
/etc/ld.so.conf.d/libc.conf
/sbin/ldconfig
/usr/bin/catchsegv
/usr/bin/getconf
/usr/bin/getent
/usr/bin/iconv
/usr/bin/ldd
/usr/bin/locale
/usr/bin/localedef
/usr/bin/pldd
/usr/bin/tzselect
/usr/bin/zdump
/usr/sbin/iconvconfig
/usr/sbin/zic
/XXXXX
/etc/apt/apt.conf.d/70debconf
/etc/debconf.conf
/usr/bin/debconf
/usr/bin/debconf-apt-progress
/usr/bin/debconf-communicate
/usr/bin/debconf-copydb
/usr/bin/debconf-escape
/usr/bin/debconf-set-selections
/usr/bin/debconf-show
/usr/sbin/dpkg-preconfigure
/usr/sbin/dpkg-reconfigure
/usr/share/debconf
/usr/share/perl5/Debconf
/usr/share/perl5/Debian
/usr/share/pixmaps/debian-logo.pngG
/XXXXX
/usr/bin/mawk
/XXXXX
/bin/dash
/bin/sh
/XXXXX`

const wildcard string = `/usr/lib/x86_64-linux-gnu/libapt-*
`

func main() {
	ws := bufio.NewScanner(strings.NewReader(wildcard))
	for ws.Scan() {
		glob, _ := filepath.Glob(ws.Text())
		for _, f := range glob {
			os.Remove(f)
		}
	}
	s := bufio.NewScanner(strings.NewReader(files))
	for s.Scan() {
		os.RemoveAll(s.Text())
	}
}
