#!/bin/sh
rm -f util-buildah.tar.xz
rm -f bin/*
printf "[+] Compiling...\\n"
for f in cmd/*
do
/usr/bin/env GOOS=linux CGO_ENABLED=0 go build -trimpath -o "bin/${f##cmd/}" -ldflags '-s -w -extldflags "-static"' "./$f"
done
printf "[+] Archiving...\\n"
tar -C bin -cJf util-buildah.tar.xz .
printf "[+] Hash...\\n"
sha256sum util-buildah.tar.xz > util-buildah.tar.xz.SHA256
printf "[!] Done.\\n"
